### PR TITLE
Service slim to latest main

### PR DESCRIPTION
**Pull request by voronoipotato**
Not sure this is ever worth merging but I tried to use the latest main and added the changes that were here in service_slim. Everything appeared to compile with a couple small changes in fable, and a couple small tweaks to this (more clear in my repo), but take it "free as in puppy". I am way out of my league on this one, but hopefully the fact that I was able to copy your code with some small changes and everything still compiled may give you hope for when you plan to update everything.  I'd be curious to know whether it "actually works" or just compiles, but only if you're bored. I'd hate to waste your time.

Thanks!

### CODE REVIEW

**Comment by ncave** [comment]
@voronoipotato Normally we only rebase from upstream when there is a major FCS release, or F# language feature that is needed. Is that the case here, is there an upstream F# or FCS version or feature or commit that you want to target?
(I freely admit I don't follow FCS releases that close, so perhaps it's that time).

**Comment by ncave** [comment]
@voronoipotato Just to provide some perspective, yes, the `service_slim` branch is intentionally kept a minimal facade that usually needs a very light effort to be rebased from upstream. The `fable` branch on the other hand is a somewhat larger effort, as there is a lot of customization to make FCS compilable with Fable. Usually the effort level depends on the amount of code churn in upstream repo since the last merge.

**Comment by voronoipotato** [comment]
I was mostly trying to understand what the process would look like. It actually wasn't that bad, but don't take this as pressure to do this I was just bored. I was able to get fable to compile with this later version of core/fcs with a few small changes, so the good news is when you do decide to do it, it wasn't that painful.

**Comment by ncave** [comment]
@voronoipotato Had to do a fresh rebase as there was quite a churn in the upstream repo recently. Closing this, please see #2.

**Pull request closed without merging**
